### ISSUE TITLE
Purpose of :expiring_first?

### ISSUE THREAD

**Issue by madmatt** [arkadiyt/symantec-certificate-checker#4]
Hey there,

I've just run this script over some sites we host, and I think I'm getting the opposite results to what I thought?

I have the list of M66 and M70 sites, but the ones that are listed as `expiring_first` all have expiry dates that are after the M66/M70 deadline, and vice versa for those that are not listed as `expiring_first`.

Before I raise a pull request to reverse the boolean logic, I just wanted to make sure my understanding is correct:

If the script returns `expiring_first`, this should mean that the certificate will expire *before* the M66 / M70 deadline, is that right?

If so, I'll raise a PR. I've made a few changes and written a usage guide to make it a bit easier for someone who's never used Ruby before to pick up :)

**Comment by madmatt** [comment]
One other question while I'm at it - I'm not a Ruby expert at all, but aren't the fudge factors incorrect?

You've got the deadlines as being:
```ruby
M66_DEADLINE = Time.utc(2018, 4, 17+7)
M70_DEADLINE = Time.utc(2018, 10, 23+7)
```

Wouldn't you want the deadline to be a week before those dates (so `17-7`)? Otherwise it would be counted as a certificate that's expiring first, when it's actually expiring after the deadline so needs to be replaced before the deadline, right?

**Comment by madmatt** [comment]
Finally, I should say - thanks a lot for the tool! A heck of a lot easier than checking ~1000 hosts by hand! I ended up writing a PHP script to parse the JSON output into an easier to read text list, because there's quite a lot of dupes (SNI certs that cover multiple domains). Would that be worth contributing back? It's in PHP because that's what I know best :)

**Comment by madmatt** [comment]
After having seen pull request #3, I believe this is indeed incorrect, so I've gone ahead and made a pull request for it and am closing this now :)

**Comment by arkadiyt** [comment]
Hey Matt,

First off sorry for the delay on these responses, and thanks for submitting these PRs. If the code has been a useful starting point for your checks then that's great, but I think extra additions/fixes/etc should go into your custom checker or a fork - I didn't have plans to keep this repo maintained, I pushed it out as part of the blog post (exactly so that people could use it as a starting point) for informational purposes.

I'll merge #5 since it fixes a legit bug (thanks for finding!) but close the remaining PRs.

**Comment by madmatt** [comment]
Fair enough, thanks for providing the tool anyway! :)
